# Import

In [3]:
import pandas as pd
import numpy as np

# Stock

In [6]:
# Reproducible dummy values
rng = np.random.default_rng(42)
rng

# Bestand im Jahr 2026
bestand_jahr = 2026
bestand_jahr

2026

In [7]:
segmente = [
    "MINIS",
    "KLEINWAGEN",
    "KOMPAKTKLASSE",
    "MITTELKLASSE",
    "OBERE MITTELKLASSE",
    "OBERKLASSE",
    "SUVs",
    "GELÄNDEWAGEN",
    "SPORTWAGEN",
    "MINI-VANS",
    "GROSSRAUM-VANS",
    "UTILITIES",
    "WOHNMOBILE",
]

segmente

['MINIS',
 'KLEINWAGEN',
 'KOMPAKTKLASSE',
 'MITTELKLASSE',
 'OBERE MITTELKLASSE',
 'OBERKLASSE',
 'SUVs',
 'GELÄNDEWAGEN',
 'SPORTWAGEN',
 'MINI-VANS',
 'GROSSRAUM-VANS',
 'UTILITIES',
 'WOHNMOBILE']

In [8]:
antriebe = [
    "Benzin",
    "Diesel",
    "Flüssiggas (LPG) (einschl. bivalent)",
    "Erdgas (CNG) (einschl. bivalent)",
    "Elektro (BEV)",
    "Hybrid",
    "Sonstige",
]

antriebe

['Benzin',
 'Diesel',
 'Flüssiggas (LPG) (einschl. bivalent)',
 'Erdgas (CNG) (einschl. bivalent)',
 'Elektro (BEV)',
 'Hybrid',
 'Sonstige']

In [9]:
zulassungsjahre = list(range(2025, 1981, -1))  # 2025 ... 1982
zulassungsjahre

[2025,
 2024,
 2023,
 2022,
 2021,
 2020,
 2019,
 2018,
 2017,
 2016,
 2015,
 2014,
 2013,
 2012,
 2011,
 2010,
 2009,
 2008,
 2007,
 2006,
 2005,
 2004,
 2003,
 2002,
 2001,
 2000,
 1999,
 1998,
 1997,
 1996,
 1995,
 1994,
 1993,
 1992,
 1991,
 1990,
 1989,
 1988,
 1987,
 1986,
 1985,
 1984,
 1983,
 1982]

In [10]:
# Optional: slightly different scale per antrieb for more realistic-looking dummy data
antrieb_faktoren = {
    "Benzin": 1.00,
    "Diesel": 0.75,
    "Flüssiggas (LPG) (einschl. bivalent)": 0.08,
    "Erdgas (CNG) (einschl. bivalent)": 0.05,
    "Elektro (BEV)": 0.35,
    "Hybrid": 0.28,
    "Sonstige": 0.03,
}

# Optional: slightly different scale per segment
segment_faktoren = {
    "MINIS": 0.7,
    "KLEINWAGEN": 1.2,
    "KOMPAKTKLASSE": 1.4,
    "MITTELKLASSE": 1.1,
    "OBERE MITTELKLASSE": 0.8,
    "OBERKLASSE": 0.4,
    "SUVs": 1.5,
    "GELÄNDEWAGEN": 0.5,
    "SPORTWAGEN": 0.25,
    "MINI-VANS": 0.35,
    "GROSSRAUM-VANS": 0.3,
    "UTILITIES": 0.9,
    "WOHNMOBILE": 0.2,
}

bestand_2026 = {}

for segment in segmente:
    bestand_2026[segment] = {}

    for antrieb in antriebe:
        factor = segment_faktoren[segment] * antrieb_faktoren[antrieb]

        counts = []
        for jahr in zulassungsjahre:
            alter = bestand_jahr - jahr

            # Base curve: newer cars more frequent than very old ones
            base = max(50, int(12000 / (1 + alter * 0.22)))

            # Add some random variation
            value = int(base * factor * rng.uniform(0.8, 1.2))

            counts.append(value)

        df = pd.DataFrame(
            {
                "Jahr der ersten Zulassung": zulassungsjahre,
                "Anzahl Fahrzeuge": counts,
            }
        )

        bestand_2026[segment][antrieb] = df

print(bestand_2026["SUVs"]["Elektro (BEV)"].head())

   Jahr der ersten Zulassung  Anzahl Fahrzeuge
0                       2025              5074
1                       2024              4189
2                       2023              4265
3                       2022              3186
4                       2021              3036

In [12]:
bestand_2026["GELÄNDEWAGEN"]["Benzin"]

    Jahr der ersten Zulassung  Anzahl Fahrzeuge
0                        2025              4126
1                        2024              3793
2                        2023              3489
3                        2022              2606
4                        2021              2797
5                        2020              2343
6                        2019              2260
7                        2018              2108
8                        2017              2318
9                        2016              1702
10                       2015              2030
11                       2014              1599
12                       2013              1446
13                       2012              1471
14                       2011              1349
15                       2010              1198
16                       2009              1266
17                       2008              1041
18                       2007              1089
19                       2006              1140
20                       2005              1030
21                       2004              1160
22                       2003               893
23                       2002              1134
24                       2001              1028
25                       2000              1059
26                       1999               981
27                       1998               717
28                       1997               821
29                       1996               684
30                       1995               864
31                       1994               771
32                       1993               657
33                       1992               829
34                       1991               583
35                       1990               689
36                       1989               714
37                       1988               527
38                       1987               650
39                       1986               689
40                       1985               494
41                       1984               588
42                       1983               518
43                       1982               598

Wie viele Geländewagen mit Benzinantrieb gibt es aktuell?

In [13]:
bestand_2026["GELÄNDEWAGEN"]["Benzin"]["Anzahl Fahrzeuge"].sum()

np.int64(59849)

# New vehicles

In [20]:
# Reproducible dummy values
rng = np.random.default_rng(123)

segmente = [
    "MINIS",
    "KLEINWAGEN",
    "KOMPAKTKLASSE",
    "MITTELKLASSE",
    "OBERE MITTELKLASSE",
    "OBERKLASSE",
    "SUVs",
    "GELÄNDEWAGEN",
    "SPORTWAGEN",
    "MINI-VANS",
    "GROSSRAUM-VANS",
    "UTILITIES",
    "WOHNMOBILE",
]

antriebe = [
    "Benzin",
    "Diesel",
    "Flüssiggas (LPG) (einschl. bivalent)",
    "Erdgas (CNG) (einschl. bivalent)",
    "Elektro (BEV)",
    "Hybrid",
    "Sonstige",
]

jahre_neuzugang = list(range(2026, 2051))  # 2026 ... 2050

# Dummy assumptions by segment
segment_faktoren = {
    "MINIS": 0.8,
    "KLEINWAGEN": 1.1,
    "KOMPAKTKLASSE": 1.3,
    "MITTELKLASSE": 1.0,
    "OBERE MITTELKLASSE": 0.7,
    "OBERKLASSE": 0.3,
    "SUVs": 1.4,
    "GELÄNDEWAGEN": 0.4,
    "SPORTWAGEN": 0.2,
    "MINI-VANS": 0.25,
    "GROSSRAUM-VANS": 0.2,
    "UTILITIES": 0.9,
    "WOHNMOBILE": 0.15,
}

# Dummy assumptions by powertrain
antrieb_faktoren = {
    "Benzin": 0.9,
    "Diesel": 0.5,
    "Flüssiggas (LPG) (einschl. bivalent)": 0.03,
    "Erdgas (CNG) (einschl. bivalent)": 0.02,
    "Elektro (BEV)": 1.0,
    "Hybrid": 0.7,
    "Sonstige": 0.02,
}

neuzugänge = {}

for segment in segmente:
    neuzugänge[segment] = {}

    for antrieb in antriebe:
        factor = segment_faktoren[segment] * antrieb_faktoren[antrieb]
        counts = []

        for jahr in jahre_neuzugang:
            # Simple dummy trend assumptions:
            # - Benzin / Diesel decrease over time
            # - Elektro increases
            # - Hybrid rises first, then slowly falls
            # - LPG / CNG / Sonstige remain low
            if antrieb == "Benzin":
                base = max(200, 8000 - (jahr - 2026) * 220)
            elif antrieb == "Diesel":
                base = max(50, 5000 - (jahr - 2026) * 180)
            elif antrieb == "Elektro (BEV)":
                base = 2500 + (jahr - 2026) * 260
            elif antrieb == "Hybrid":
                if jahr <= 2035:
                    base = 1800 + (jahr - 2026) * 120
                else:
                    base = 2880 - (jahr - 2035) * 90
                    base = max(300, base)
            elif antrieb == "Flüssiggas (LPG) (einschl. bivalent)":
                base = max(10, 220 - (jahr - 2026) * 8)
            elif antrieb == "Erdgas (CNG) (einschl. bivalent)":
                base = max(5, 160 - (jahr - 2026) * 7)
            else:  # Sonstige
                base = max(5, 100 - (jahr - 2026) * 2)

            value = int(base * factor * rng.uniform(0.85, 1.15))
            counts.append(max(0, value))

        df = pd.DataFrame(
            {
                "Jahr des Neuzugangs": jahre_neuzugang,
                "Anzahl Fahrzeuge": counts,
            }
        )

        neuzugänge[segment][antrieb] = df

# Example
print(neuzugänge["GELÄNDEWAGEN"]["Benzin"])

    Jahr des Neuzugangs  Anzahl Fahrzeuge
0                  2026              2680
1                  2027              2426
2                  2028              3110
3                  2029              2488
4                  2030              2227
5                  2031              2760
6                  2032              2438
7                  2033              2374
8                  2034              2167
9                  2035              2271
10                 2036              1964
11                 2037              2064
12                 2038              1783
13                 2039              1808
14                 2040              1632
15                 2041              1905
16                 2042              1606
17                 2043              1578
18                 2044              1499
19                 2045              1532
20                 2046              1296
21                 2047              1383
22                 2048              1241
23                 2049              1182
24                 2050              1004

In [21]:
neuzugänge["GROSSRAUM-VANS"]["Elektro (BEV)"]

    Jahr des Neuzugangs  Anzahl Fahrzeuge
0                  2026               528
1                  2027               570
2                  2028               617
3                  2029               593
4                  2030               690
5                  2031               828
6                  2032               753
7                  2033               755
8                  2034               966
9                  2035              1041
10                 2036              1120
11                 2037              1109
12                 2038              1055
13                 2039              1060
14                 2040              1156
15                 2041              1088
16                 2042              1234
17                 2043              1376
18                 2044              1580
19                 2045              1380
20                 2046              1360
21                 2047              1501
22                 2048              1796
23                 2049              1925
24                 2050              1525

# Außerbetriebsetzungen

In [23]:
# Reproducible dummy values
rng = np.random.default_rng(456)

jahre_ausserbetriebsetzung = list(range(2026, 2051))  # 2026 ... 2050
zulassungsjahre = list(range(2025, 1981, -1))         # 2025 ... 1982

segmente = [
    "MINIS",
    "KLEINWAGEN",
    "KOMPAKTKLASSE",
    "MITTELKLASSE",
    "OBERE MITTELKLASSE",
    "OBERKLASSE",
    "SUVs",
    "GELÄNDEWAGEN",
    "SPORTWAGEN",
    "MINI-VANS",
    "GROSSRAUM-VANS",
    "UTILITIES",
    "WOHNMOBILE",
]

antriebe = [
    "Benzin",
    "Diesel",
    "Flüssiggas (LPG) (einschl. bivalent)",
    "Erdgas (CNG) (einschl. bivalent)",
    "Elektro (BEV)",
    "Hybrid",
    "Sonstige",
]

# Dummy scaling by segment
segment_faktoren = {
    "MINIS": 0.8,
    "KLEINWAGEN": 1.2,
    "KOMPAKTKLASSE": 1.3,
    "MITTELKLASSE": 1.0,
    "OBERE MITTELKLASSE": 0.7,
    "OBERKLASSE": 0.4,
    "SUVs": 1.1,
    "GELÄNDEWAGEN": 0.5,
    "SPORTWAGEN": 0.2,
    "MINI-VANS": 0.35,
    "GROSSRAUM-VANS": 0.3,
    "UTILITIES": 0.9,
    "WOHNMOBILE": 0.15,
}

# Dummy scaling by powertrain
antrieb_faktoren = {
    "Benzin": 1.0,
    "Diesel": 0.8,
    "Flüssiggas (LPG) (einschl. bivalent)": 0.06,
    "Erdgas (CNG) (einschl. bivalent)": 0.04,
    "Elektro (BEV)": 0.2,
    "Hybrid": 0.15,
    "Sonstige": 0.03,
}

ausserbetriebsetzungen = {}

for exit_jahr in jahre_ausserbetriebsetzung:
    ausserbetriebsetzungen[exit_jahr] = {}

    for segment in segmente:
        ausserbetriebsetzungen[exit_jahr][segment] = {}

        for antrieb in antriebe:
            factor = segment_faktoren[segment] * antrieb_faktoren[antrieb]
            counts = []

            for zul_jahr in zulassungsjahre:
                alter = exit_jahr - zul_jahr

                # Dummy assumption:
                # older vehicles are more likely to be taken out of service
                # future first registrations relative to exit year are impossible
                if alter < 0:
                    base = 0
                elif alter <= 2:
                    base = 40
                elif alter <= 5:
                    base = 120
                elif alter <= 8:
                    base = 350
                elif alter <= 12:
                    base = 900
                elif alter <= 16:
                    base = 1800
                elif alter <= 20:
                    base = 2600
                elif alter <= 25:
                    base = 3200
                elif alter <= 30:
                    base = 3800
                else:
                    base = 4200

                value = int(base * factor * rng.uniform(0.85, 1.15))
                counts.append(max(0, value))

            df = pd.DataFrame(
                {
                    "Jahr der ersten Zulassung": zulassungsjahre,
                    "Anzahl Fahrzeuge": counts,
                }
            )

            ausserbetriebsetzungen[exit_jahr][segment][antrieb] = df

# Example access
print(ausserbetriebsetzungen[2026]["GELÄNDEWAGEN"]["Benzin"])
print(ausserbetriebsetzungen[2035]["SUVs"]["Diesel"])

    Jahr der ersten Zulassung  Anzahl Fahrzeuge
0                        2025                20
1                        2024                17
2                        2023                61
3                        2022                54
4                        2021                52
5                        2020               170
6                        2019               171
7                        2018               169
8                        2017               425
9                        2016               429
10                       2015               436
11                       2014               414
12                       2013              1003
13                       2012               768
14                       2011               976
15                       2010               802
16                       2009              1172
17                       2008              1294
18                       2007              1282
19                       2006              1286
20                       2005              1444
21                       2004              1478
22                       2003              1392
23                       2002              1622
24                       2001              1826
25                       2000              1745
26                       1999              2009
27                       1998              1985
28                       1997              1886
29                       1996              1741
30                       1995              2146
31                       1994              2288
32                       1993              1921
33                       1992              2387
34                       1991              2268
35                       1990              2110
36                       1989              2234
37                       1988              2009
38                       1987              2181
39                       1986              2406
40                       1985              1856
41                       1984              2287
42                       1983              2223
43                       1982              2255
    Jahr der ersten Zulassung  Anzahl Fahrzeuge
0                        2025               790
1                        2024               693
2                        2023               835
3                        2022              1402
4                        2021              1440
5                        2020              1526
6                        2019              1401
7                        2018              2401
8                        2017              1983
9                        2016              2612
10                       2015              2068
11                       2014              2603
12                       2013              2778
13                       2012              2724
14                       2011              3019
15                       2010              2867
16                       2009              3711
17                       2008              3812
18                       2007              3566
19                       2006              3582
20                       2005              3183
21                       2004              3678
22                       2003              3932
23                       2002              3866
24                       2001              3773
25                       2000              4229
26                       1999              3956
27                       1998              4107
28                       1997              3934
29                       1996              3699
30                       1995              4237
31                       1994              4232
32                       1993              3350
33                       1992              3693
34                       1991              3769
35                       1990              4199
36                       1989              3896
37                       1988              3263
38                       1987              3212
39                       1986              3166
40                       1985              3926
41                       1984              3314
42                       1983              3908
43                       1982              3696

# Leeres Dictionary Bestand

In [25]:
jahre_bestand = list(range(2026, 2051))  # 2026 ... 2050
zulassungsjahre = list(range(2025, 1981, -1))  # 2025 ... 1982

segmente = [
    "MINIS",
    "KLEINWAGEN",
    "KOMPAKTKLASSE",
    "MITTELKLASSE",
    "OBERE MITTELKLASSE",
    "OBERKLASSE",
    "SUVs",
    "GELÄNDEWAGEN",
    "SPORTWAGEN",
    "MINI-VANS",
    "GROSSRAUM-VANS",
    "UTILITIES",
    "WOHNMOBILE",
]

antriebe = [
    "Benzin",
    "Diesel",
    "Flüssiggas (LPG) (einschl. bivalent)",
    "Erdgas (CNG) (einschl. bivalent)",
    "Elektro (BEV)",
    "Hybrid",
    "Sonstige",
]

bestand = {}

for jahr in jahre_bestand:
    bestand[jahr] = {}

    for segment in segmente:
        bestand[jahr][segment] = {}

        for antrieb in antriebe:
            bestand[jahr][segment][antrieb] = pd.DataFrame(
                {
                    "Jahr der ersten Zulassung": zulassungsjahre,
                    "Anzahl Fahrzeuge": [None] * len(zulassungsjahre),
                }
            )

# Example access
print(bestand[2026]["GELÄNDEWAGEN"]["Benzin"])

    Jahr der ersten Zulassung Anzahl Fahrzeuge
0                        2025             None
1                        2024             None
2                        2023             None
3                        2022             None
4                        2021             None
5                        2020             None
6                        2019             None
7                        2018             None
8                        2017             None
9                        2016             None
10                       2015             None
11                       2014             None
12                       2013             None
13                       2012             None
14                       2011             None
15                       2010             None
16                       2009             None
17                       2008             None
18                       2007             None
19                       2006             None
20                       2005             None
21                       2004             None
22                       2003             None
23                       2002             None
24                       2001             None
25                       2000             None
26                       1999             None
27                       1998             None
28                       1997             None
29                       1996             None
30                       1995             None
31                       1994             None
32                       1993             None
33                       1992             None
34                       1991             None
35                       1990             None
36                       1989             None
37                       1988             None
38                       1987             None
39                       1986             None
40                       1985             None
41                       1984             None
42                       1983             None
43                       1982             None